name: hollywood-kz6fittycent
version: 1.12.2
summary: fill your console with Hollywood melodrama technobabble
description: >
    This utility will split your console into a multiple panes of genuine
    technobabble, perfectly suitable for any Hollywood geek melodrama.
    It is particularly suitable on any number of computer consoles in the
    background of any excellent schlock technothriller.
confinement: devmode
grade: stable

parts:
  hollywood:
    plugin: nil
    build-packages:
      - byobu
    stage-packages: 
      - hollywood
      - glibc-source
      - time
      - byobu
    
    stage:
        - -bin/hollywood
    snap:
        - -bin/hollywood

apps:
   hollywood:
     command: hollywood
     environment: 
       LC_ALL: C.UTF-8
